<?php

namespace NoticeBoardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NoticeCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticeCategoryRepository extends EntityRepository
{
}
